# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# specific branch build with batching
trigger:
  batch: true
  branches:
    include:
    - main

variables:
  - group: PipelineVariables

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  displayName: Set .NET version
  inputs:
    packageType: 'sdk'
    version: $(dotnet_version)
  
- task: Bash@3
  displayName: Install MAUI workloads
  inputs:
    targetType: 'inline'
    script: |
      dotnet nuget locals all --clear
      dotnet workload install android ios maui --source https://aka.ms/dotnet9/nuget/index.json --source https://api.nuget.org/v3/index.json 

- task: Bash@3
  displayName: Show current working directory
  inputs:
    targetType: 'inline'
    script: 'ls'

- task: Bash@3
  displayName: Build windows MAUI app
  inputs:
    targetType: 'inline'
    script: |
      dotnet publish maui_pipeline/MAUITestApp/MAUITestApp.csproj -f net9.0-windows10.0.19041.0 -c Release --output '$(Build.ArtifactStagingDirectory)/Windows'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Windows app to artifacts' 
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/windows'
    ArtifactName: 'Windows'