# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# specific branch build with batching
trigger:
  batch: true
  branches:
    include:
    - main

variables:
  - group: PipelineVariables

stages:
  - stage: windows_android_stage
    displayName: Windows and Android stages
    pool:
      name: Azure Pipeline
      vmImage: windows-latest
    jobs:
      - job: windows_job
        displayName: Windows job
        steps:
        - template: setup_template.yml

        - task: Bash@3
          displayName: Build Windows MAUI app
          inputs:
            targetType: 'inline'
            script: |
              dotnet publish MAUITestApp/MAUITestApp.csproj -f net9.0-windows10.0.19041.0 -c Release --output '$(Build.ArtifactStagingDirectory)/Windows'

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Windows app to artifacts' 
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/windows'
            ArtifactName: 'Windows'

      - job: android_job
        dependsOn:
          - windows_job
        displayName: Android job
        steps:
        - template: setup_template.yml

        - task: Bash@3
          displayName: Build Android MAUI app
          inputs:
            targetType: 'inline'
            script: |
                  dotnet publish MAUITestApp/MAUITestApp.csproj -f net9.0-android -c Release --output '$(Build.ArtifactStagingDirectory)/Android'

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Android app to artifacts' 
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/android'
            ArtifactName: 'Android'